### ISSUE TITLE
Question: how to install to the local maven repo?

### ISSUE THREAD

**Issue by javadba** [linkedin/scanns#1]
What is the equivalent of `mvn install` ?  I did look at `gradlew tasks` and did not see `install` as supported.

**Comment by namitk** [comment]
Could you explain what you intend to accomplish?

In any case, do https://stackoverflow.com/questions/6122252/gradle-alternate-to-mvn-install or https://discuss.gradle.org/t/what-is-the-preferred-gradle-approach-to-locally-install-an-artifact-equivalent-to-mavens-install/5592 help?

**Comment by namitk** [comment]
Please reopen if it's still an issue.
